-- Widgets table seeds here (Example)
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Crypto Caveman', 1, 200, 'The Crypto Cavemen Club is an exclusive NFT community comprised of the worlds most prehistoric generation of humans.', 'https://arweave.net/5bsHPca-P77gZY1WVOBVpg7ug0BmzdtMiph2qDGyev4/5670.png', '2019-12-27', TRUE, FALSE );
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Degenerate Ape', 2, 150, 'The Degenerate Ape Academy is an NFT brand housed on the Solana blockchain. The academy consists of 10,000 degenerate ape NFTs.', 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/1069x1069/filters:format(webp)/data.solanart.io/img/degenape/7294.jpg', '2020-11-17', TRUE, FALSE );
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Rude Golem', 3, 250, '8,888 Rude Golems are here to protect their planet and most importantly YOU. Dont be intimidated tho, they are pretty nice when you get to know them', 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/600x600/filters:format(webp)/www.arweave.net/D5oFcCEGyUn3ZzKhCjKLyoKNZCBPaHZzLydchSDsspw/data.png', '2021-10-07', TRUE, FALSE);
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Cat Punk', 2, 350, 'Where NFT utilities meet high-quality 3D art' , 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/600x600/filters:format(webp)/www.arweave.net/T1tH6vd3VZ75l6QpWLZhBgJjmRj_J-8CRm5IlNaL_-0/data.png', '2021-10-07', TRUE, FALSE);
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Degen Trash panda', 3, 400, 'An underground collective of scavengers.' , 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/600x600/filters:format(webp)/www.arweave.net/h01qMvpwiSRDaNWGVKDjLAjCBElOOKuBZ0cBn2LWxfA/data.png', '2019-06-07', TRUE, FALSE);
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Sol Chicks', 1, 220, 'SolChicks is the leading NFT-powered fantasy playing game built on the Solana blockchain.' , 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/600x600/filters:format(webp)/ipfs.io/ipfs/bafybeigfquussktyq73c4jd5m2nkkzvqwz543mxn6qymmdlhjbrwsxecwa/solchicks-3404.png', '2021-05-07', TRUE, FALSE);
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Spookeletons', 1, 185, 'A collection of 6.666 Spookeletons that are all different, algorithmically generated, fierce, and collectible.' , 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/600x600/filters:format(webp)/arweave.net/s1m2vNdjoak3oSkh2gwEeepU5SfWlnod9HfWIchQaRU/data.png', '2020-02-07', TRUE, FALSE);
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Danerob', 3, 375, 'A collection of 3,000 uniquely generated robotic great danes' , 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/600x600/filters:format(webp)/www.arweave.net/DldRwy8N85HDPJjGkQajVJAgSO_nb6dimCUFdbTMDvw/data.png', '2021-1-07', TRUE, FALSE);
INSERT INTO products (title, owner_id, price, description, image, date_created, is_active, is_sold) VALUES ('Aurorian', 3, 500, 'The villagers from the whole country have gathered in Neftiville for the party, meet the Aurorians.' , 'https://hkgwtdvfyh.medianetwork.cloud/unsafe/512x640/filters:format(webp)/data.solanart.io/img/aurory/AuroryProject/7463.png', '2019-10-07', TRUE, FALSE);
